/**
*					--DAO Generator--
*
* Java code generated by the DAO Generator Developed By Akcess.in 
* Date of file generation: Sun Feb 26 09:00:19 COT 2006
*
* DAO Generator Version 1.0
*
*/
package com.unal.convenio.sip.admin.voh;
import com.unal.convenio.sip.common.vo.BaseVo;
import java.sql.Timestamp;
import com.unal.convenio.sip.admin.voh.TablaReferenciaVo;

/**
* DataTransferObject for the domain entity tsip_persona
*/
public class PersonaVo extends BaseVo
{
	private Integer id_persona;
	private TablaReferenciaVo idref_tipopersona;
	private TablaReferenciaVo idref_tipodocumento;
	private String documento;
	private String nombre1;
	private String nombre2;
	private String apellido1;
	private String apellido2;
	private String email;
	private String telefono;


	public PersonaVo(){
            idref_tipopersona = new TablaReferenciaVo();
            idref_tipodocumento = new TablaReferenciaVo();
        }
	public PersonaVo(Integer id_persona ,TablaReferenciaVo idref_tipopersona ,TablaReferenciaVo idref_tipodocumento ,String documento ,String nombre1 ,String nombre2 ,String apellido1 ,String apellido2 ,String email ,String telefono){
		this.id_persona = id_persona;
		this.idref_tipopersona = idref_tipopersona;
		this.idref_tipodocumento = idref_tipodocumento;
		this.documento = documento;
		this.nombre1 = nombre1;
		this.nombre2 = nombre2;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.email = email;
		this.telefono = telefono;
	}

	public void setId_persona(Integer id_persona ){
		 this.id_persona =id_persona;
	}
	public Integer getId_persona(){
		 return(id_persona);
	}
	public void setIdref_tipopersona(TablaReferenciaVo idref_tipopersona ){
		 this.idref_tipopersona =idref_tipopersona;
	}
	public TablaReferenciaVo getIdref_tipopersona(){
		 return(idref_tipopersona);
	}
	public void setIdref_tipodocumento(TablaReferenciaVo idref_tipodocumento ){
		 this.idref_tipodocumento =idref_tipodocumento;
	}
	public TablaReferenciaVo getIdref_tipodocumento(){
		 return(idref_tipodocumento);
	}
	public void setDocumento(String documento ){
		 this.documento =documento;
	}
	public String getDocumento(){
		 return(documento);
	}
	public void setNombre1(String nombre1 ){
		 this.nombre1 =nombre1;
	}
	public String getNombre1(){
		 return(nombre1);
	}
	public void setNombre2(String nombre2 ){
		 this.nombre2 =nombre2;
	}
	public String getNombre2(){
		 return(nombre2);
	}
	public void setApellido1(String apellido1 ){
		 this.apellido1 =apellido1;
	}
	public String getApellido1(){
		 return(apellido1);
	}
	public void setApellido2(String apellido2 ){
		 this.apellido2 =apellido2;
	}
	public String getApellido2(){
		 return(apellido2);
	}
	public void setEmail(String email ){
		 this.email =email;
	}
	public String getEmail(){
		 return(email);
	}
	public void setTelefono(String telefono ){
		 this.telefono =telefono;
	}
	public String getTelefono(){
		 return(telefono);
	}

        //Para poder mostrarlo como una columna en la tabla
	public String toString(){
		StringBuffer ret = new StringBuffer();                
		ret.append((nombre1 != null ? nombre1 + " " : ""));
                ret.append((nombre2 != null ? nombre2 + " ": ""));
                ret.append((apellido1 != null ? apellido1 + " ": ""));
                ret.append((apellido2 != null ? apellido2: ""));                
		return ret.toString();
	}       
        
        public String getEtiqueta() {
            return toString();
        }

        public Integer getId() {
            return id_persona;
        }            
        
        public PersonaVo getCopia(){
            PersonaVo vo = new PersonaVo();
            vo.setId_persona(id_persona);
            vo.setIdref_tipopersona(idref_tipopersona);
            vo.setIdref_tipodocumento(idref_tipodocumento);
            vo.setDocumento(documento);
            vo.setNombre1(nombre1); 
            vo.setNombre2(nombre2); 
            vo.setApellido1(apellido1);  
            vo.setApellido2(apellido2); 
            vo.setEmail(email); 
            vo.setTelefono(telefono);
            return vo;
        }
        
        
}//End
