/**
*					--DAO Generator--
*
* Java code generated by the DAO Generator Developed By Pravu Mishra 
* Date of file generation: Sat Feb 11 23:31:39 COT 2006
*
* DAO Generator Version 0.0.1
*
*/
package com.unal.convenio.sip.admin.voh;
import com.unal.convenio.sip.common.vo.BaseVo;
import java.sql.Timestamp;
import java.util.Set;
import java.util.HashSet;
/**
* DataTransferObject for the domain entity TSIP_TIPO_REFERENCIA
*/
public class TipoReferenciaVo extends BaseVo{
	private Integer id_tiporeferencia;
	private String nombre;
	private String descripcion;
	private String abreviacion;
        private Set referencias = new HashSet();

	public TipoReferenciaVo(){}
	public TipoReferenciaVo(Integer id_tiporeferencia ,String nombre ,String descripcion ,String abreviacion){
		this.id_tiporeferencia = id_tiporeferencia;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.abreviacion = abreviacion;
	}

	public void setId_tiporeferencia(Integer id_tiporeferencia ){
		 this.id_tiporeferencia =id_tiporeferencia;
	}
	public Integer getId_tiporeferencia(){
		 return(id_tiporeferencia);
	}
	public void setNombre(String nombre ){
		 this.nombre =nombre;
	}
	public String getNombre(){
		 return(nombre);
	}
	public void setDescripcion(String descripcion ){
		 this.descripcion =descripcion;
	}
	public String getDescripcion(){
		 return(descripcion);
	}
	public void setAbreviacion(String abreviacion ){
		 this.abreviacion =abreviacion;
	}
	public String getAbreviacion(){
		 return(abreviacion);
	}
        public void setReferencias(Set referencias){
                this.referencias = referencias;
        }
        public Set getReferencias(){
                return(referencias);
        }

        public String getEtiqueta() {
            return nombre;
        }

        public Integer getId() {
            return id_tiporeferencia;
        }       	
}//End
