/**
*					--DAO Generator--
*
* Java code generated by the DAO Generator Developed By Akcess.in 
* Date of file generation: Wed Mar 01 09:34:19 COT 2006
*
* DAO Generator Version 1.0
*
*/
package com.unal.convenio.sip.admin.voh;
import com.unal.convenio.sip.common.vo.BaseVo;
import com.unal.convenio.sip.admin.voh.PersonaVo;
import java.io.Serializable;
import org.hibernate.Hibernate;
import java.util.Set;
import java.util.HashSet;


/**
* DataTransferObject for the domain entity tsip_admin_usuario
*/
public class UsuarioVo extends BaseVo 
{
	private Integer id_usuario;
	private PersonaVo persona;
	private String login;
        private Boolean disabled;
        private Set roles = new HashSet();
        private byte[] password;
        
	public UsuarioVo(){}
	public UsuarioVo(Integer id_usuario ,PersonaVo persona ,String login, Boolean disabled){
            this.disabled = disabled;	
            this.id_usuario = id_usuario;
            this.persona = persona;
            this.login = login;
	}

	public void setId_usuario(Integer id_usuario ){
             this.id_usuario =id_usuario;
	}
	public Integer getId_usuario(){
             return(id_usuario);
	}
	public void setPersona(PersonaVo persona ){
             this.persona =persona;
	}
	public PersonaVo getPersona(){
             return(persona);
	}
	public void setLogin(String login ){
             this.login =login;
	}
	public String getLogin(){
             return(login);
	}
        public void setPassword(byte[] password ){
             this.password = password;
	}
	public byte[] getPassword(){
             return(password);
	}
	public void setDisabled(Boolean disabled ){
            boolean bDisabled = true;
            if( disabled == null || !disabled.booleanValue()){
                bDisabled = false;
            }
            this.disabled = new Boolean(bDisabled);
	}
	public Boolean getDisabled(){
             return(disabled);
	}

        public void setRoles(Set roles){
            this.roles = roles;
        }
        public Set getRoles(){
            return(roles);
        }
        
	public String toString(){
            return (login != null ? login : "");
	}    
        
        public boolean equals(Object obj) {
            boolean retValue = false;
            if( obj instanceof UsuarioVo && obj != null){
                UsuarioVo tmp = (UsuarioVo)obj;
                if( tmp.getId_usuario() != null ){
                    retValue = tmp.getId_usuario().equals(id_usuario);
                }
            }
            return retValue;
        }

        public int hashCode() {           
            return id_usuario.intValue();
        }                       

        public String getEtiqueta() {
            return login;
        }

        public Integer getId() {
            return id_usuario;
        }
}//End
